"""

Revision ID: 47d6367ed482
Revises: f66b6991fb39
Create Date: 2026-01-31 13:31:26.111467

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47d6367ed482"
down_revision: Union[str, Sequence[str], None] = "f66b6991fb39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "breeds", sa.Column("short_name", sa.String(length=63), nullable=True)
    )
    op.add_column(
        "coat_color", sa.Column("short_name", sa.String(length=63), nullable=True)
    )
    op.add_column(
        "horse",
        sa.Column("this_stable", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("horse", "this_stable")
    op.drop_column("coat_color", "short_name")
    op.drop_column("breeds", "short_name")
    # ### end Alembic commands ###
