"""

Revision ID: 4ec9b0c636d5
Revises: 
Create Date: 2025-11-22 13:30:18.470743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ec9b0c636d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('page_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeds_name'), 'breeds', ['name'], unique=False)
    op.create_table('coat_color',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('page_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coat_color_name'), 'coat_color', ['name'], unique=False)
    op.create_table('horse_owner',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('type', sa.String(length=7), nullable=False),
    sa.Column('address', sa.String(length=511), nullable=True),
    sa.Column('phone_numbers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horse_owner_name'), 'horse_owner', ['name'], unique=False)
    op.create_table('horse_service',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_formatter', sa.String(length=7), nullable=False),
    sa.Column('page_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horse_service_name'), 'horse_service', ['name'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('path', sa.String(length=511), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_name'), 'photos', ['name'], unique=False)
    op.create_table('price_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_groups_name'), 'price_groups', ['name'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('page_data', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('price_tables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_name'), 'prices', ['name'], unique=False)
    op.create_index(op.f('ix_prices_slug'), 'prices', ['slug'], unique=False)
    op.create_table('user_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope_name', sa.String(length=63), nullable=False, comment='Название области доступа'),
    sa.Column('scope_description', sa.String(length=255), nullable=True, comment='Описание области доступа'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scopes_scope_name'), 'user_scopes', ['scope_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('username', sa.String(length=63), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=63), nullable=True, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(length=63), nullable=True, comment='Фамилия пользователя'),
    sa.Column('middle_name', sa.String(length=63), nullable=True, comment='Отчество пользователя (необязательно)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('horse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('breed_id', sa.UUID(), nullable=True),
    sa.Column('coat_color_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=7), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=7), nullable=False),
    sa.Column('bdate', sa.Date(), nullable=True),
    sa.Column('ddate', sa.Date(), nullable=True),
    sa.Column('bdate_mode', sa.String(length=7), nullable=False),
    sa.Column('ddate_mode', sa.String(length=7), nullable=False),
    sa.Column('horse_owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coat_color_id'], ['coat_color.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['horse_owner_id'], ['horse_owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horse_name'), 'horse', ['name'], unique=False)
    op.create_index(op.f('ix_horse_slug'), 'horse', ['slug'], unique=False)
    op.create_table('price_groups_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['price_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.String(length=1023), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_scopes_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['user_scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horse_children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horse_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['horse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horse_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horse_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horse_service_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('horse_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('description_override', sa.String(length=511), nullable=True),
    sa.Column('price_override', sa.Integer(), nullable=True),
    sa.Column('price_formatter_override', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['horse_service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horse_service_relations')
    op.drop_table('horse_photos')
    op.drop_table('horse_children')
    op.drop_table('user_scopes_relations')
    op.drop_table('tokens')
    op.drop_table('price_photos')
    op.drop_table('price_groups_relations')
    op.drop_index(op.f('ix_horse_slug'), table_name='horse')
    op.drop_index(op.f('ix_horse_name'), table_name='horse')
    op.drop_table('horse')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_scopes_scope_name'), table_name='user_scopes')
    op.drop_table('user_scopes')
    op.drop_index(op.f('ix_prices_slug'), table_name='prices')
    op.drop_index(op.f('ix_prices_name'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_price_groups_name'), table_name='price_groups')
    op.drop_table('price_groups')
    op.drop_index(op.f('ix_photos_name'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_horse_service_name'), table_name='horse_service')
    op.drop_table('horse_service')
    op.drop_index(op.f('ix_horse_owner_name'), table_name='horse_owner')
    op.drop_table('horse_owner')
    op.drop_index(op.f('ix_coat_color_name'), table_name='coat_color')
    op.drop_table('coat_color')
    op.drop_index(op.f('ix_breeds_name'), table_name='breeds')
    op.drop_table('breeds')
    # ### end Alembic commands ###
