"""

Revision ID: 8215ddc78865
Revises: 4ec9b0c636d5
Create Date: 2025-11-22 13:44:07.497084

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8215ddc78865"
down_revision: Union[str, Sequence[str], None] = "4ec9b0c636d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("breeds", sa.Column("slug", sa.String(length=63), nullable=False))
    op.alter_column("breeds", "page_data", existing_type=sa.TEXT(), nullable=False)
    op.create_index(op.f("ix_breeds_slug"), "breeds", ["slug"], unique=False)
    op.add_column("coat_color", sa.Column("slug", sa.String(length=63), nullable=False))
    op.alter_column("coat_color", "page_data", existing_type=sa.TEXT(), nullable=False)
    op.create_index(op.f("ix_coat_color_slug"), "coat_color", ["slug"], unique=False)
    op.add_column(
        "horse_service", sa.Column("slug", sa.String(length=63), nullable=False)
    )
    op.alter_column(
        "horse_service", "page_data", existing_type=sa.TEXT(), nullable=False
    )
    op.create_index(
        op.f("ix_horse_service_slug"), "horse_service", ["slug"], unique=False
    )
    op.alter_column("prices", "page_data", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prices", "page_data", existing_type=sa.TEXT(), nullable=True)
    op.drop_index(op.f("ix_horse_service_slug"), table_name="horse_service")
    op.alter_column(
        "horse_service", "page_data", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_column("horse_service", "slug")
    op.drop_index(op.f("ix_coat_color_slug"), table_name="coat_color")
    op.alter_column("coat_color", "page_data", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("coat_color", "slug")
    op.drop_index(op.f("ix_breeds_slug"), table_name="breeds")
    op.alter_column("breeds", "page_data", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("breeds", "slug")
    # ### end Alembic commands ###
