"""prices

Revision ID: 8f07dfa0bb46
Revises: d788ce3f2cae
Create Date: 2025-11-08 12:34:51.371301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f07dfa0bb46'
down_revision: Union[str, Sequence[str], None] = 'd788ce3f2cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=31), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_formatter', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group', name='uq_name_group')
    )
    op.create_index(op.f('ix_prices_name'), 'prices', ['name'], unique=False)
    op.create_table('price_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_formatter', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'price_id', name='uq_name_price_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_variants')
    op.drop_index(op.f('ix_prices_name'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
