"""create tables

Revision ID: d788ce3f2cae
Revises:
Create Date: 2025-11-08 10:27:59.901918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d788ce3f2cae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_scopes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "scope_name",
            sa.String(length=63),
            nullable=False,
            comment="Название области доступа",
        ),
        sa.Column(
            "scope_description",
            sa.String(length=255),
            nullable=True,
            comment="Описание области доступа",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_scopes_scope_name"), "user_scopes", ["scope_name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("username", sa.String(length=63), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "first_name",
            sa.String(length=63),
            nullable=True,
            comment="Имя пользователя",
        ),
        sa.Column(
            "last_name",
            sa.String(length=63),
            nullable=True,
            comment="Фамилия пользователя",
        ),
        sa.Column(
            "middle_name",
            sa.String(length=63),
            nullable=True,
            comment="Отчество пользователя (необязательно)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("value", sa.String(length=1023), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_scopes_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["scope_id"], ["user_scopes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_scopes_relations")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_scopes_scope_name"), table_name="user_scopes")
    op.drop_table("user_scopes")
    # ### end Alembic commands ###
