"""

Revision ID: da3ea601e50f
Revises: 8215ddc78865
Create Date: 2025-11-29 20:12:22.480208

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da3ea601e50f"
down_revision: Union[str, Sequence[str], None] = "8215ddc78865"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_breeds_name"), table_name="breeds")
    op.create_index(op.f("ix_breeds_name"), "breeds", ["name"], unique=True)
    op.drop_index(op.f("ix_coat_color_name"), table_name="coat_color")
    op.create_index(op.f("ix_coat_color_name"), "coat_color", ["name"], unique=True)
    op.drop_index(op.f("ix_horse_service_name"), table_name="horse_service")
    op.create_index(
        op.f("ix_horse_service_name"), "horse_service", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_horse_service_name"), table_name="horse_service")
    op.create_index(
        op.f("ix_horse_service_name"), "horse_service", ["name"], unique=False
    )
    op.drop_index(op.f("ix_coat_color_name"), table_name="coat_color")
    op.create_index(op.f("ix_coat_color_name"), "coat_color", ["name"], unique=False)
    op.drop_index(op.f("ix_breeds_name"), table_name="breeds")
    op.create_index(op.f("ix_breeds_name"), "breeds", ["name"], unique=False)
    # ### end Alembic commands ###
