"""

Revision ID: f66b6991fb39
Revises: 1564690d218b
Create Date: 2025-12-06 14:17:28.165058

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f66b6991fb39"
down_revision: Union[str, Sequence[str], None] = "1564690d218b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("key", sa.String(length=63), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.Column("description", sa.String(length=511), nullable=True),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_site_settings_key"), "site_settings", ["key"], unique=True)
    op.create_index(
        op.f("ix_site_settings_name"), "site_settings", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_settings_name"), table_name="site_settings")
    op.drop_index(op.f("ix_site_settings_key"), table_name="site_settings")
    op.drop_table("site_settings")
    # ### end Alembic commands ###
