from typing import Protocol


class SecurityProtocol(Protocol):
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, plain_password: str, hashed_password: str) -> bool: ...
    def create_access_token(self, sub: str) -> str: ...
    def create_refresh_token(self, sub: str) -> str: ...
    def decode_token(self, token: str) -> dict: ...
