import { KNOWN_USER_SCOPES } from "@/types/api/user";
import { useUserContext } from "@/contexts/UserContext";
import { useCallback, useEffect } from "react";

export enum PRICE_PAGE_SCOPES_ACTIONS {
    SEE_USER_INSTRUCTIONS = "see_user_instructions",
    SEE_DEVELOPER_INSTRUCTIONS = "see_developer_instructions",
    PRICE_GROUP_RETRIEVE = "price_group_retrieve",
    PRICE_GROUP_CREATE = "price_group_create",
    PRICE_GROUP_UPDATE_NAME = "price_group_update_name",
    PRICE_GROUP_UPDATE_DESCRIPTION = "price_group_update_description",
    PRICE_GROUP_UPDATE = "price_group_update",
    PRICE_GROUP_DELETE = "price_group_delete",
    PRICE_RETRIEVE = "price_retrieve",
    PRICE_CREATE = "price_create",
    PRICE_UPDATE_GROUPS = "price_update_groups",
    PRICE_UPDATE_NAME = "price_update_name",
    PRICE_UPDATE_DESCRIPTION = "price_update_description",
    PRICE_UPDATE_TABLES = "price_update_tables",
    PRICE_UPDATE_PHOTOS = "price_update_photos",
    PRICE_UPDATE_PAGE_DATA = "price_update_page_data",
    PRICE_UPDATE = "price_update",
    PRICE_DELETE = "price_delete",
}

export const pricePageScopesRegistry: Record<PRICE_PAGE_SCOPES_ACTIONS, KNOWN_USER_SCOPES[]> = {
    [PRICE_PAGE_SCOPES_ACTIONS.SEE_USER_INSTRUCTIONS]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.SEE_DEVELOPER_INSTRUCTIONS]: [KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_GROUP_RETRIEVE]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_GROUP_CREATE]: [KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_GROUP_UPDATE_NAME]: [KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_GROUP_UPDATE_DESCRIPTION]: [KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_GROUP_UPDATE]: [KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_GROUP_DELETE]: [KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_RETRIEVE]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_CREATE]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_UPDATE_GROUPS]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_UPDATE_NAME]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_UPDATE_DESCRIPTION]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_UPDATE]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_UPDATE_TABLES]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_UPDATE_PHOTOS]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_UPDATE_PAGE_DATA]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
    [PRICE_PAGE_SCOPES_ACTIONS.PRICE_DELETE]: [KNOWN_USER_SCOPES.ADMIN, KNOWN_USER_SCOPES.DEVELOPER],
}

export const usePricePageActionScopes = () => {
    const { scopes } = useUserContext();

    const hasPermission = useCallback((action: PRICE_PAGE_SCOPES_ACTIONS) => {
        return pricePageScopesRegistry[action].some(scope => scopes.includes(scope));
    }, [scopes]);

    return {
        hasPermission,
    };
};

